# Classe del controlador JDBC per la base de dades SQLite
hibernate.connection.driver_class=org.sqlite.JDBC

# URL de connexi\u00c3\u00b3 a la base de dades SQLite al directori data
hibernate.connection.url=jdbc:sqlite:./data/database-pr23.db

# Dialecte per mantenir la compatibilitat amb SQLite
hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

# Mostra les consultes SQL a la consola (true/false)
hibernate.show_sql=false

# Estrat\u00c3\u00a8gia de generaci\u00c3\u00b3 autom\u00c3\u00a0tica de l'esquema
# Opcions:
# validate: Valida l'esquema sense fer canvis
# update: Actualitza l'esquema si \u00c3\u00a9s necessari
# create: Crea l'esquema, destruint les dades anteriors
# create-drop: Crea l'esquema a l'inici i l'esborra al tancar
# none: Desactiva la generaci\u00c3\u00b3 autom\u00c3\u00a0tica
hibernate.hbm2ddl.auto=create